In [17]:
#!pip install "cloud-sql-python-connector[pymysql]"
#!pip install sqlalchemy
#!pip install mysql-connector-python
# !pip install google-cloud-storage

In [18]:
import sqlite3
from google.cloud import storage 
import pandas as pd
import numpy as np
from datetime import datetime
import mysql.connector
import sys
from cred import MYSQL_PASSWORD

In [19]:
#### Establish Connetion ####

connection = mysql.connector.connect(
    user='root', 
    password=MYSQL_PASSWORD, 
    host='34.30.80.103',
    database='mercari_db')

cursor = connection.cursor()

In [20]:
# Execute your query
query1 = "SELECT * FROM product_listing"
cursor.execute(query1)

# Fetch column names
column_names = [i[0] for i in cursor.description]

# Create a DataFrame from the query result
frame = pd.DataFrame(cursor.fetchall(), columns=column_names)

# Close cursor and connection
cursor.close()
connection.close()

# Display the DataFrame
frame.head()

,id,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description,created_at,last_updated_at
0,1,793697,Plaid Vest,2,Women/Coats & Jackets/Vest,Old Navy,11.0,1,Green and blue. Very thick and soft! Perfect f...,2022-01-01 00:00:00,2022-01-01 00:00:00
1,2,402094,Women's Sperrys,3,Women/Shoes/Loafers & Slip-Ons,Sperrys,21.0,0,EUC,2022-01-01 00:01:00,2022-01-01 00:01:00
2,3,522439,Grey sweater dress,1,Women/Dresses/Other,Fashion Nova,20.0,1,This is a heather grey sweater dress from fash...,2022-01-01 00:01:00,2022-01-01 00:01:00
3,4,214455,Tory Burch 'Perry' Leather Wallet,3,Women/Women's Accessories/Wallets,Tory Burch,91.0,0,Tory Burch 'Perry' Leather Zip Continental Wal...,2022-01-01 00:03:00,2022-01-01 00:03:00
4,5,902755,Fujifilm Rainbow Instax Film,1,Electronics/Cameras & Photography/Film Photogr...,Fuji,14.0,0,No description yet,2022-01-01 00:05:00,2022-01-01 00:05:00

In [22]:
# https://stackoverflow.com/questions/73493052/how-to-connect-to-cloud-sql-using-python